services:
    # тупо веб сервис наш, fastapi штуки тут
    web:
        # в нашем случае есть build, говорит в какой папке искать dockerfile, чтобы собрать образ и потом сохранить в виде image ↑
        build: .
        # 1. либо использует существующий образ из docker hub, если указан только image (без build)
        # 2. либо создает образ на ваш профиль, используя локальный dockerfile, если есть build
        image: academy-examples/redis-lecture
        # переопределяем название контейнера (если не трогать, то будет имя сервиса использовано)
        container_name: web-app
        # настройка зависимости от других контейнеров, нам нужна редиска до старта веба
        depends_on:
            redis:
                condition: service_started
        # подключение конфига с переменными среды (можно создать список из нескольких и отметить, какие обязательны, а что нет)
        env_file: 
        - path: ./.env
          required: false 
        #
        ports:
            - "8000:8000"
    # редиска
    redis:
        image: redis:latest
        container_name: redis-service
        
        environment:
            - REDIS_PASSWORD=admin_pass
            - REDIS_USER=redis_user
            - REDIS_USER_PASSWORD=redis_user_pass
        # открыли порты, чтобы 63879КОМПЬЮТЕРА перекидывал все приходящие на него пакеты внутрь контейнера на порт 6380КОНТЕЙНЕРНЫЙ
        ports:
            - "6379:6380"
        # выделяем пространство с нашего диска для контейнера - гарантируем постоянное хранилище для базы данных редиски
        # левая часть - относительный путь до локального хранилища на компе; правая часть путь до виртуального хранилища внутри контейнера
        volumes:
            - ./data/redis_data:/redis_data_docker
        # требуем от сервиса перезапусков, пока не получится включится
        # если возникнет крит ошибка, то не поможет конечно(бесконечный рестарт),
        # но например, если ресурсы недовыделились, то позволит рано или поздно включить
        restart: unless-stopped